### ISSUE TITLE
All link broken

### ISSUE THREAD

**Issue by fosfrancesco** [ksandom/installUltraMotion#1]
Thank you for your guide! Unfortunately all links for SDK v2 are now broken. 
Any idea of where we can find them? Or is it possible to share them in this repo, since they are not available anywhere in the web?

**Comment by ksandom** [comment]
Sorry, I've only just noticed your post.

You're right. I'll take a look tomorrow, and think through the best solutions.

Out of interest, which OS are you using?

**Comment by ksandom** [comment]
Apparently I haven't gone back to bed yet :D

Here are some links (As before, you'll need to be logged in to download them.):

* [x] [Linux](https://leap2.ultraleap.com/download/software?name=tracking-software&version=2.3.1&platform=linux).
* [x] [Windows](https://leap2.ultraleap.com/download/software?name=tracking-software&version=2.3.1&platform=windows).
* [ ] MacOS.

I've got the Linux and Windows links working, but haven't figured out the MacOS link yet.

## Experimentation for MacOS

Things I've tried:

* https://leap2.ultraleap.com/download/software?name=tracking-software&version=2.3.1&platform=mac
* https://leap2.ultraleap.com/download/software?name=tracking-software&version=2.3.1&platform=macos-intel
* https://leap2.ultraleap.com/download/software?name=tracking-software&version=2.3.1&platform=macos
* https://leap2.ultraleap.com/download/software?name=tracking-software&version=2.3.1&platform=osx
* https://leap2.ultraleap.com/download/software?name=tracking-software&version=3.2.1&platform=macos-intel
* https://leap2.ultraleap.com/download/software?name=tracking-software&version=3.2.1&platform=macos
* https://leap2.ultraleap.com/download/software?name=tracking-software&version=3.2.1&platform=mac

The [old link](https://developer.leapmotion.com/releases/mac-2-3-1) was simply "mac".

If someone knows what it is, please comment with the link.

## Notes

* As before, you need to be logged in to download the SDK.
* It seems they invalidated accounts that existed before July 2023. so I needed to sign up again, and I guess that others will need to do so as well.

**Comment by ksandom** [comment]
It looks like 2.3.1 for MacOS [won't happen](https://discord.com/channels/994213697490800670/1125810590284259489/1184813184633278474):

> HI @Shelle699 , the V2 SDK is not compatible with any versions of MacOS from Big Sur onwards. We won't be bringing this back as this is over 9 years old now and obsolete. I would recommend contacting the developers of Isadora and asking them if they have any plans to update their software to support Gemini V5. 👍 

I'll be putting time into updating [handWavey](https://github.com/ksandom/handWavey) to use the new versions soon. In the mean time it will still work on Windows and Linux.
